ForumBundle\Entity\SubCategory:
    type: entity
    table: null
    repositoryClass: ForumBundle\Repository\SubCategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        subCategoryName:
            type: string
            length: 255
            unique: true
        description:
            type: string
            length: 255
        slug:
            type: string
            length: 255
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: subcategories
            joinColumn: 
                name: category_id
                referencedColumnName: id
    oneToMany:
        topics:
            targetEntity: Topic
            mappedBy: subCategory
    lifecycleCallbacks: { 
        prePersist: [setSlug]
     }
