ForumBundle\Entity\Topic:
    type: entity
    table: null
    repositoryClass: ForumBundle\Repository\TopicRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        topicName:
            type: string
            length: 255
        description:
            type: string
            length: 255
        slug:
            type: string
            length: 255
    manyToOne:
        subCategory:
            targetEntity: SubCategory
            inversedBy: topics
            joinColumn:
                name: subcategory_id
                referencedColumnName: id
    oneToMany:
        messages:
            targetEntity: Message
            mappedBy: topic
    lifecycleCallbacks: { 
        prePersist: [setSlug]
     }
