forum_homepage:
    path:     /
    defaults: { _controller: ForumBundle:Default:index }

view_categories:
    path:     /categories
    defaults: { _controller: ForumBundle:Category:viewCategories }

create_category:
    path:     /categories/create
    defaults: { _controller: ForumBundle:Category:createCategory }

update_category:
    path:     /categories/{slug}
    defaults: { _controller: ForumBundle:Category:updateCategory }

delete_categories:
    path:     /categories/{id}
    defaults: { _controller: ForumBundle:Category:deleteCategories }

view_subcategories:
    path:     /categories/{slug}/subcategories
    defaults: { _controller: ForumBundle:SubCategory:viewSubCategory }

create_subcategory:
    path:     /categories/{slug}/subcategories/create
    defaults: { _controller: ForumBundle:SubCategory:createSubCategory }

update_subcategory:
    path:     /categories/{slug}/subcategories/{subCatSlug}
    defaults: { _controller: ForumBundle:SubCategory:updateSubCategory }

delete_subcategory:
    path:     /categories/{id}/subcategories/{subCatId}
    defaults: { _controller: ForumBundle:SubCategory:deleteSubCategory }

view_topics:
    path:     /categories/{slug}/subcategories/{subCatSlug}/topics
    defaults: { _controller: ForumBundle:Topic:viewTopics }

create_topic:
    path:     /categories/{id}/subcategories/{subCatId}/topics/create
    defaults: { _controller: ForumBundle:Topic:createTopic }

update_topic:
    path:     /categories/{id}/subcategories/{subCatId}/topics/{topicId}
    defaults: { _controller: ForumBundle:Topic:updateTopic }

delete_topic:
    path:     /categories/{id}/subcategories/{subCatId}/topics/{topicId}
    defaults: { _controller: ForumBundle:Topic:deleteTopic }

view_messages:
    path:     /messages
    defaults: { _controller: ForumBundle:MessageController:viewMessages }

create_message:
    path:     /messages
    defaults: { _controller: ForumBundle:MessageController:createMessage }

update_message:
    path:     /messages/{id}
    defaults: { _controller: ForumBundle:MessageController:updateMessage }

delete_message:
    path:     /messages/{id}
    defaults: { _controller: ForumBundle:MessageController:deleteMessage }
