<?php

namespace ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;
use ForumBundle\Entity\SubCategory;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Ajout d'une subcategory
     *
     * @param ForumBundle\Entity\SubCategory $subcategory
     * @return subcategory
     */
    public function addSubCategory(SubCategory $subcategory){
        $this->_em->persist($subcategory);
        $this->_em->flush();
        return $subcategory;
    }

    /**
     * Récupération d'une subcategory grâce au slug
     *
     * @param String $slug
     * @return $category
     */
    public function findBySlug(String $slug){
        $query = $this->_em
        ->getRepository('ForumBundle:Category')
        ->createQueryBuilder('S')
        ->setParameter('param', $slug)
        ->select('S')
        ->where('S.categorySlug=:param')
        ->getQuery();

        $subcategories = $query->getSingleResult();
        
        return $subcategories;
    }

    //mthd editCategry à créer
}
