<?php

namespace ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;
use ForumBundle\Entity\Topic;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Ajout d'un topic
     *
     * @param ForumBundle\Entity\Topic $topic
     * @return topic
     */
    public function addTopic(Topic $topic){
        $this->_em->persist($topic);
        $this->_em->flush();
        return $topic;
    }
}
